from pathlib import Path
import sqlite3

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


DB_PATH = Path("db/nifty100.db")
OUTPUT_DIR = Path("output")
REPORTS_DIR = Path("reports")

FEATURES = [
    "return_on_equity_pct",
    "debt_to_equity",
    "revenue_cagr_5yr",
    "fcf_cagr_5yr",
    "operating_profit_margin_pct",
]


def load_cluster_data():
    """Load cluster labels and latest KPI data for all companies."""
    labels = pd.read_csv(OUTPUT_DIR / "cluster_labels.csv")

    conn = sqlite3.connect(DB_PATH)

    ratios = pd.read_sql_query(
        """
        SELECT
            company_id,
            year,
            return_on_equity_pct,
            debt_to_equity,
            revenue_cagr_5yr,
            operating_profit_margin_pct,
            free_cash_flow_cr
        FROM financial_ratios
        """,
        conn,
    )

    companies = pd.read_sql_query(
        """
        SELECT id AS company_id, company_name
        FROM companies
        """,
        conn,
    )

    conn.close()

    ratios["year"] = pd.to_numeric(ratios["year"], errors="coerce")
    ratios = ratios.sort_values(["company_id", "year"])

    latest = ratios.groupby("company_id", as_index=False).tail(1)

    data = labels.merge(
        companies,
        on="company_id",
        how="left",
    )

    data = data.merge(
        latest.drop(columns=["year"]),
        on="company_id",
        how="left",
    )

    # FCF CAGR is not stored in financial_ratios.
    # Use cluster-analysis data generated by the clustering script
    # if available; otherwise leave it for portfolio reporting.
    if "fcf_cagr_5yr" not in data.columns:
        data["fcf_cagr_5yr"] = np.nan

    return data


def generate_cluster_profiles(data):
    """Create cluster mean and median profiles."""
    profile_mean = (
        data.groupby(["cluster_id", "cluster_name"])[FEATURES]
        .mean()
        .round(4)
    )

    profile_median = (
        data.groupby(["cluster_id", "cluster_name"])[FEATURES]
        .median()
        .round(4)
    )

    mean_path = OUTPUT_DIR / "cluster_profiles_mean.csv"
    median_path = OUTPUT_DIR / "cluster_profiles_median.csv"

    profile_mean.to_csv(mean_path)
    profile_median.to_csv(median_path)

    print(f"  {mean_path}")
    print(f"  {median_path}")


def generate_correlation_heatmap(data):
    """Generate correlation heatmap for 10 latest-year KPIs."""

    conn = sqlite3.connect(DB_PATH)

    kpis = pd.read_sql_query(
        """
        SELECT
            company_id,
            year,
            net_profit_margin_pct,
            operating_profit_margin_pct,
            return_on_equity_pct,
            debt_to_equity,
            interest_coverage,
            asset_turnover,
            roce_pct,
            roa_pct,
            composite_quality_score
        FROM financial_ratios
        """,
        conn,
    )

    conn.close()

    kpis["year"] = pd.to_numeric(kpis["year"], errors="coerce")

    latest = (
        kpis.sort_values(["company_id", "year"])
        .groupby("company_id", as_index=False)
        .tail(1)
    )

    correlation = latest.drop(
        columns=["company_id", "year"]
    ).corr()

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(12, 10))
    plt.imshow(
        correlation,
        interpolation="nearest",
        aspect="auto",
    )
    plt.colorbar()

    labels = correlation.columns.tolist()

    plt.xticks(
        range(len(labels)),
        labels,
        rotation=45,
        ha="right",
    )
    plt.yticks(range(len(labels)), labels)

    plt.title("Nifty 100 Latest-Year KPI Correlation Heatmap")
    plt.tight_layout()

    path = REPORTS_DIR / "correlation_heatmap.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"  {path}")


def generate_outlier_report(data):
    """Detect KPI outliers using sector-level Z-scores."""

    # broad_sector may not exist in cluster_labels.
    # Use cluster_name as a stable grouping fallback.
    group_col = (
        "broad_sector"
        if "broad_sector" in data.columns
        else "cluster_name"
    )

    records = []

    for group_name, group in data.groupby(group_col):
        for feature in FEATURES:
            values = pd.to_numeric(
                group[feature],
                errors="coerce",
            )

            mean = values.mean()
            std = values.std(ddof=0)

            if pd.isna(std) or std == 0:
                continue

            zscores = (values - mean) / std

            for idx in group.index[zscores.abs() > 3]:
                records.append(
                    {
                        "company_id": data.loc[idx, "company_id"],
                        "company_name": data.loc[idx, "company_name"],
                        "group": group_name,
                        "kpi": feature,
                        "value": data.loc[idx, feature],
                        "z_score": zscores.loc[idx],
                    }
                )

    report = pd.DataFrame(
        records,
        columns=[
            "company_id",
            "company_name",
            "group",
            "kpi",
            "value",
            "z_score",
        ],
    )

    path = OUTPUT_DIR / "outlier_report.csv"
    report.to_csv(path, index=False)

    print(f"  {path}")
    print(f"  Outliers detected: {len(report)}")


def generate_portfolio_stats(data):
    """Generate P10/P25/P50/P75/P90/Mean/Std statistics."""

    rows = []

    for feature in FEATURES:
        values = pd.to_numeric(
            data[feature],
            errors="coerce",
        ).dropna()

        rows.append(
            {
                "kpi": feature,
                "P10": values.quantile(0.10),
                "P25": values.quantile(0.25),
                "P50": values.quantile(0.50),
                "P75": values.quantile(0.75),
                "P90": values.quantile(0.90),
                "Mean": values.mean(),
                "Std": values.std(),
            }
        )

    stats = pd.DataFrame(rows).round(4)

    path = OUTPUT_DIR / "portfolio_stats.csv"
    stats.to_csv(path, index=False)

    print(f"  {path}")


def run_cluster_analysis():
    """Run all Sprint 6 Day 37 analytics."""
    print("=" * 60)
    print("SPRINT 6 DAY 37 — CLUSTER ANALYSIS")
    print("=" * 60)

    data = load_cluster_data()

    print(f"Companies analyzed : {len(data)}")
    print()

    generate_cluster_profiles(data)
    generate_correlation_heatmap(data)
    generate_outlier_report(data)
    generate_portfolio_stats(data)

    print()
    print("Day 37 outputs generated successfully.")
    print("=" * 60)


if __name__ == "__main__":
    run_cluster_analysis()